[general]
resolution = [1024, 1024]
caption_extension = ".txt"
batch_size = 4
enable_bucket = true
bucket_no_upscale = false

[[datasets]]
image_directory = "/workspace/video_me/assets/male_model/training/images/rudra"
cache_directory = "/workspace/video_me/assets/male_model/training/cache/rudra"
num_repeats = 60
