[general]
caption_extension = ".txt"
keep_tokens = 1
shuffle_caption = false

[[datasets]]
resolution = [768, 768]
batch_size = 1
enable_bucket = true
bucket_no_upscale = false

  [[datasets.subsets]]
  image_dir = "assets/kids_duo/training/images/max"
  num_repeats = 15
