[general]
resolution = [1024, 1024]
caption_extension = ".txt"
batch_size = 4
enable_bucket = true
bucket_no_upscale = false

[[datasets]]
image_directory = "/workspace/video_me/assets/kids_duo/training/images/max"
cache_directory = "/workspace/video_me/assets/kids_duo/training/cache/max"
num_repeats = 60
