"""Generate the code map under docs/code_map/ from the project source via AST.

The map is the project's "knowledge graph as flat files": per-package API
listings, the capability->adapter mapping, module dependency edges, Pydantic
model fields, dashboard routes, and env vars. Output is deterministic so
tests/test_code_map.py can assert docs/code_map/ is in sync with the code.

Regenerate with:  python -m scripts.generate_code_map
"""

from __future__ import annotations

import ast
import sys
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT_DIR = REPO_ROOT / "docs" / "code_map"

# Packages whose classes/functions are documented in detail.
DETAIL_PACKAGES = ("core", "adapters", "services", "scripts")
# Extra directories listed in INDEX.md (one line per file) but not detailed.
INDEX_ONLY_PACKAGES = ("tests",)
# Curated files inside the output dir that the generator must never touch.
CURATED_FILES = {"LIMITATIONS.md"}

HEADER = "<!-- AUTO-GENERATED by scripts/generate_code_map.py — do not edit. Regenerate: python -m scripts.generate_code_map -->\n"


@dataclass
class FunctionInfo:
    name: str
    signature: str
    doc: str
    is_async: bool


@dataclass
class ClassInfo:
    name: str
    bases: list[str]
    doc: str
    methods: list[FunctionInfo]
    fields: list[tuple[str, str, str]]  # (name, annotation, default)


@dataclass
class ModuleInfo:
    path: Path  # relative to repo root
    doc: str
    classes: list[ClassInfo] = field(default_factory=list)
    functions: list[FunctionInfo] = field(default_factory=list)
    project_imports: list[str] = field(default_factory=list)

    @property
    def dotted(self) -> str:
        parts = self.path.with_suffix("").parts
        if parts[-1] == "__init__":
            parts = parts[:-1]
        return ".".join(parts)


def first_doc_line(node: ast.AST) -> str:
    doc = ast.get_docstring(node)  # type: ignore[arg-type]
    if not doc:
        return ""
    return doc.strip().splitlines()[0].strip()


def format_signature(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    args = ast.unparse(node.args)
    returns = f" -> {ast.unparse(node.returns)}" if node.returns else ""
    return f"({args}){returns}"


def collect_functions(body: list[ast.stmt]) -> list[FunctionInfo]:
    out: list[FunctionInfo] = []
    for node in body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            out.append(
                FunctionInfo(
                    name=node.name,
                    signature=format_signature(node),
                    doc=first_doc_line(node),
                    is_async=isinstance(node, ast.AsyncFunctionDef),
                )
            )
    return out


def collect_class(node: ast.ClassDef) -> ClassInfo:
    fields: list[tuple[str, str, str]] = []
    for stmt in node.body:
        if isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name):
            default = ast.unparse(stmt.value) if stmt.value is not None else ""
            fields.append((stmt.target.id, ast.unparse(stmt.annotation), default))
        elif isinstance(stmt, ast.Assign) and len(stmt.targets) == 1 and isinstance(
            stmt.targets[0], ast.Name
        ):
            # Unannotated class attrs (e.g. `name = "fetch_media"` on capability ABCs).
            fields.append((stmt.targets[0].id, "", ast.unparse(stmt.value)))
    return ClassInfo(
        name=node.name,
        bases=[ast.unparse(base) for base in node.bases],
        doc=first_doc_line(node),
        methods=collect_functions(node.body),
        fields=fields,
    )


def project_import_targets(node: ast.stmt) -> list[str]:
    roots = tuple(DETAIL_PACKAGES)
    targets: list[str] = []
    if isinstance(node, ast.Import):
        targets = [alias.name for alias in node.names]
    elif isinstance(node, ast.ImportFrom) and node.module and node.level == 0:
        targets = [node.module]
    return [t for t in targets if t.split(".")[0] in roots]


def parse_module(path: Path) -> ModuleInfo | None:
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except SyntaxError:
        return None
    info = ModuleInfo(path=path.relative_to(REPO_ROOT), doc=first_doc_line(tree))
    info.functions = collect_functions(tree.body)
    info.classes = [collect_class(n) for n in tree.body if isinstance(n, ast.ClassDef)]
    imports: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            imports.update(project_import_targets(node))
    info.project_imports = sorted(imports)
    return info


def iter_python_files(package: str) -> list[Path]:
    root = REPO_ROOT / package
    if not root.exists():
        return []
    return sorted(
        p
        for p in root.rglob("*.py")
        if "__pycache__" not in p.parts and ".venv" not in p.parts
    )


# ---------------------------------------------------------------------------
# Renderers
# ---------------------------------------------------------------------------


def render_module_section(mod: ModuleInfo) -> list[str]:
    lines = [f"### `{mod.path}`", ""]
    if mod.doc:
        lines += [mod.doc, ""]
    for cls in mod.classes:
        bases = f"({', '.join(cls.bases)})" if cls.bases else ""
        lines.append(f"- **class `{cls.name}{bases}`**" + (f" — {cls.doc}" if cls.doc else ""))
        for fn in cls.methods:
            prefix = "async " if fn.is_async else ""
            doc = f" — {fn.doc}" if fn.doc else ""
            lines.append(f"  - `{prefix}{fn.name}{fn.signature}`{doc}")
    for fn in mod.functions:
        prefix = "async " if fn.is_async else ""
        doc = f" — {fn.doc}" if fn.doc else ""
        lines.append(f"- `{prefix}{fn.name}{fn.signature}`{doc}")
    lines.append("")
    return lines


def render_package_page(title: str, modules: list[ModuleInfo], extra: list[str] | None = None) -> str:
    lines = [HEADER, f"# {title}", ""]
    if extra:
        lines += extra
    for mod in modules:
        if mod.path.name == "__init__.py" and not (mod.classes or mod.functions or mod.doc):
            continue
        lines += render_module_section(mod)
    return "\n".join(lines).rstrip() + "\n"


def capability_mapping(all_modules: dict[str, list[ModuleInfo]]) -> list[str]:
    """Map each Capability ABC (core/capabilities/base.py) to adapter classes."""
    abcs: dict[str, str] = {}  # class name -> stage name
    for mod in all_modules.get("core", []):
        if mod.path.as_posix() != "core/capabilities/base.py":
            continue
        for cls in mod.classes:
            stage = next((d for n, _a, d in cls.fields if n == "name"), "")
            if cls.name != "Capability":
                abcs[cls.name] = stage.strip("'\"") or cls.name
    rows: list[tuple[str, str, str]] = []  # (stage, class, module)
    for mod in all_modules.get("adapters", []):
        for cls in mod.classes:
            for base in cls.bases:
                base_name = base.split("[")[0].split(".")[-1]
                if base_name in abcs:
                    rows.append((abcs[base_name], cls.name, mod.path.as_posix()))
    rows.sort()
    lines = [
        "## Capability → adapter mapping",
        "",
        "| Stage | Adapter class | Module |",
        "|---|---|---|",
    ]
    lines += [f"| {stage} | `{cls}` | `{path}` |" for stage, cls, path in rows]
    implemented = {stage for stage, _c, _p in rows}
    orphans = sorted(set(abcs.values()) - implemented)
    if orphans:
        lines += ["", "ABCs with no adapter in `adapters/`: " + ", ".join(f"`{s}`" for s in orphans)]
    lines.append("")
    return lines


def render_models_page(all_modules: dict[str, list[ModuleInfo]]) -> str:
    """All Pydantic models (BaseModel/BaseSettings subclasses, transitively) with fields."""
    model_bases = {"BaseModel", "BaseSettings"}
    candidates: list[tuple[ModuleInfo, ClassInfo]] = []
    for mods in all_modules.values():
        for mod in mods:
            for cls in mod.classes:
                candidates.append((mod, cls))
    # Transitive closure over project-defined bases.
    known = set(model_bases)
    changed = True
    while changed:
        changed = False
        for _mod, cls in candidates:
            if cls.name in known:
                continue
            if any(base.split("[")[0].split(".")[-1] in known for base in cls.bases):
                known.add(cls.name)
                changed = True
    lines = [HEADER, "# Pydantic models", ""]
    for mod, cls in candidates:
        if cls.name not in known or cls.name in model_bases:
            continue
        bases = ", ".join(cls.bases)
        lines.append(f"### `{cls.name}` ({bases}) — `{mod.path}`")
        if cls.doc:
            lines.append(f"{cls.doc}")
        lines.append("")
        for name, annotation, default in cls.fields:
            if not annotation:  # unannotated class attrs (model_config etc.) aren't fields
                continue
            default_part = f" = `{default}`" if default else ""
            lines.append(f"- `{name}: {annotation}`{default_part}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_api_page() -> str:
    """Dashboard FastAPI routes: method, path, handler, docstring."""
    path = REPO_ROOT / "services" / "dashboard_api.py"
    tree = ast.parse(path.read_text(encoding="utf-8"))
    rows: list[tuple[str, str, str, str]] = []
    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        for dec in node.decorator_list:
            if not (isinstance(dec, ast.Call) and isinstance(dec.func, ast.Attribute)):
                continue
            method = dec.func.attr.upper()
            if method not in {"GET", "POST", "PUT", "DELETE", "PATCH"}:
                continue
            if not (dec.args and isinstance(dec.args[0], ast.Constant)):
                continue
            rows.append((str(dec.args[0].value), method, node.name, first_doc_line(node)))
    rows.sort()
    lines = [
        HEADER,
        "# Dashboard API routes (`services/dashboard_api.py`)",
        "",
        f"{len(rows)} routes.",
        "",
        "| Method | Path | Handler | Purpose |",
        "|---|---|---|---|",
    ]
    lines += [f"| {method} | `{route}` | `{fn}` | {doc} |" for route, method, fn, doc in rows]
    return "\n".join(lines) + "\n"


def render_env_page(all_modules: dict[str, list[ModuleInfo]]) -> str:
    """Env vars from the Settings class (env_prefix VIDEO_ME_)."""
    settings: ClassInfo | None = None
    for mod in all_modules.get("core", []):
        if mod.path.as_posix() == "core/config.py":
            settings = next((c for c in mod.classes if c.name == "Settings"), None)
    lines = [
        HEADER,
        "# Environment variables (`core/config.py:Settings`, prefix `VIDEO_ME_`)",
        "",
        "| Env var | Type | Default |",
        "|---|---|---|",
    ]
    if settings:
        for name, annotation, default in settings.fields:
            if not annotation or name == "model_config":
                continue
            lines.append(f"| `VIDEO_ME_{name.upper()}` | `{annotation}` | `{default}` |")
    return "\n".join(lines) + "\n"


def render_dependencies_page(all_modules: dict[str, list[ModuleInfo]]) -> str:
    lines = [
        HEADER,
        "# Module dependency edges (project-internal imports)",
        "",
        "`module` → imports. Test modules excluded.",
        "",
    ]
    for package in DETAIL_PACKAGES:
        lines += [f"## {package}/", ""]
        for mod in all_modules.get(package, []):
            if not mod.project_imports:
                continue
            targets = ", ".join(f"`{t}`" for t in mod.project_imports)
            lines.append(f"- `{mod.dotted}` → {targets}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_index_page(all_modules: dict[str, list[ModuleInfo]]) -> str:
    lines = [
        HEADER,
        "# File index — one line per module",
        "",
        "Detail pages: [core.md](core.md), [adapters.md](adapters.md), [services.md](services.md),",
        "[scripts.md](scripts.md), [models.md](models.md), [api.md](api.md), [env.md](env.md),",
        "[dependencies.md](dependencies.md), [LIMITATIONS.md](LIMITATIONS.md) (curated).",
        "",
    ]
    for package in (*DETAIL_PACKAGES, *INDEX_ONLY_PACKAGES):
        lines += [f"## {package}/", ""]
        for mod in all_modules.get(package, []):
            if mod.path.name == "__init__.py" and not mod.doc:
                continue
            doc = mod.doc or "(no module docstring)"
            lines.append(f"- `{mod.path}` — {doc}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def generate(output_dir: Path) -> dict[str, str]:
    all_modules: dict[str, list[ModuleInfo]] = {}
    for package in (*DETAIL_PACKAGES, *INDEX_ONLY_PACKAGES):
        parsed = [parse_module(p) for p in iter_python_files(package)]
        all_modules[package] = [m for m in parsed if m is not None]

    pages = {
        "INDEX.md": render_index_page(all_modules),
        "core.md": render_package_page("core/ — orchestration, models, config", all_modules["core"]),
        "adapters.md": render_package_page(
            "adapters/ — one package per pipeline stage",
            all_modules["adapters"],
            extra=capability_mapping(all_modules),
        ),
        "services.md": render_package_page(
            "services/ — dashboard + GPU service servers", all_modules["services"]
        ),
        "scripts.md": render_package_page("scripts/ — setup, checks, utilities", all_modules["scripts"]),
        "models.md": render_models_page(all_modules),
        "api.md": render_api_page(),
        "env.md": render_env_page(all_modules),
        "dependencies.md": render_dependencies_page(all_modules),
    }

    output_dir.mkdir(parents=True, exist_ok=True)
    for name, content in pages.items():
        (output_dir / name).write_text(content, encoding="utf-8")
    return pages


def main() -> int:
    output_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_OUTPUT_DIR
    pages = generate(output_dir)
    for name in sorted(pages):
        print(f"wrote {output_dir / name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
